version: '3'
services:
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
      - $PWD/conf:/usr/local/etc/redis
