version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - /mongodb-data:/data/db
    command: mongod
