
# To make this docker-compose work, we need to make
# new go.mod file => and then run go.mod download
# after that we build dodkcerfile and should
# let theme run in the default network

# nginx : http://localhost/api/tasks or
# nginx : http://192.168.99.100/api/tasks or
version: '3'
services:

  worker:
    # image: worker
    build:
      context: .
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://admin:password@192.168.99.100:27017/test?authSource=admin&readPreference=primary&ssl=false
      - MONGO_DATABASE=Go-Tasks
      - RABBITMQ_URI=amqp://user:password@192.168.99.100:5672
      - RABBITMQ_QUEUE=rss_urls
